
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import java.io.File;
import javax.imageio.ImageIO;
import java.io.IOException;
import java.awt.image.BufferedImage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Tampilan extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan
     */
    public Tampilan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        GambarDisini = new javax.swing.JLabel();
        Potong = new javax.swing.JButton();
        Zoom = new javax.swing.JLabel();
        Rotasi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ZoomBesar = new javax.swing.JButton();
        ZoomKecil = new javax.swing.JButton();
        RotasiKiri = new javax.swing.JButton();
        RotasiKanan = new javax.swing.JButton();
        CerminAtas = new javax.swing.JButton();
        CerminKiri = new javax.swing.JButton();
        KecerahanSlide = new javax.swing.JSlider();
        CheckKecerahan = new javax.swing.JCheckBox();
        MenuUtama = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadGambar = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        Negatif = new javax.swing.JMenuItem();
        HitamPutih = new javax.swing.JMenuItem();
        Grayscale = new javax.swing.JMenuItem();

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GambarDisini.setBackground(new java.awt.Color(255, 0, 0));

        Potong.setText("Potong");
        Potong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotongActionPerformed(evt);
            }
        });

        Zoom.setText("Zoom");

        Rotasi.setText("Rotasi");

        jLabel3.setText("Cermin");

        ZoomBesar.setText("Besar");
        ZoomBesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomBesarActionPerformed(evt);
            }
        });

        ZoomKecil.setText("Kecil");
        ZoomKecil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomKecilActionPerformed(evt);
            }
        });

        RotasiKiri.setText("Kiri");
        RotasiKiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotasiKiriActionPerformed(evt);
            }
        });

        RotasiKanan.setText("Kanan");
        RotasiKanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotasiKananActionPerformed(evt);
            }
        });

        CerminAtas.setText("Atas");
        CerminAtas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerminAtasActionPerformed(evt);
            }
        });

        CerminKiri.setText("Kiri");
        CerminKiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerminKiriActionPerformed(evt);
            }
        });

        KecerahanSlide.setMaximum(200);
        KecerahanSlide.setValue(100);
        KecerahanSlide.setEnabled(false);
        KecerahanSlide.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aturKecerahan(evt);
            }
        });

        CheckKecerahan.setText("Mode kecerahan");
        CheckKecerahan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                statusCekKecerahan(evt);
            }
        });

        jMenu1.setAction(jMenu1.getAction());
        jMenu1.setText("File");

        LoadGambar.setText("Load Gambar");
        LoadGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGambarActionPerformed(evt);
            }
        });
        jMenu1.add(LoadGambar);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jMenu1.add(Keluar);

        MenuUtama.add(jMenu1);

        EditMenu.setText("Edit");

        Negatif.setText("Negatif");
        Negatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegatifActionPerformed(evt);
            }
        });
        EditMenu.add(Negatif);

        HitamPutih.setText("Hitam Putih");
        HitamPutih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitamPutihActionPerformed(evt);
            }
        });
        EditMenu.add(HitamPutih);

        Grayscale.setText("Grayscale");
        Grayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayscaleActionPerformed(evt);
            }
        });
        EditMenu.add(Grayscale);

        MenuUtama.add(EditMenu);

        setJMenuBar(MenuUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(Zoom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ZoomBesar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZoomKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(GambarDisini, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RotasiKiri, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RotasiKanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Rotasi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(Potong, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckKecerahan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(409, 409, 409))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KecerahanSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(CerminAtas)
                                .addGap(37, 37, 37)
                                .addComponent(CerminKiri)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(Zoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ZoomBesar)
                            .addComponent(ZoomKecil)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(Rotasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RotasiKiri)
                            .addComponent(RotasiKanan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Potong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GambarDisini, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(CheckKecerahan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CerminAtas)
                        .addComponent(CerminKiri))
                    .addComponent(KecerahanSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void LoadGambarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        JFileChooser gbr = new JFileChooser();
        if(gbr.showOpenDialog(GambarDisini)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(gbr.getSelectedFile().getAbsolutePath());
            Image imageResized=image.getScaledInstance(550, 450, Image.SCALE_DEFAULT);
            //String imageResized = null;
            ImageIcon imageIcon=new ImageIcon(imageResized);
            
            GambarDisini.setIcon(imageIcon);
        }
        direktori(gbr.getSelectedFile().getAbsolutePath());
    }                                          

    private void direktori(String dir){
        String temp = dir;
        String newDir = temp.replace("\\", "\\\\");
        ImgDir = newDir;
    }
    
    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {                                       
         System.exit(0);  // TODO add your handling code here:
    }                                      

    private void RotasiKananActionPerformed(java.awt.event.ActionEvent evt) {                                            
         // TODO add your handling code here:
    }                                           

    private void PotongActionPerformed(java.awt.event.ActionEvent evt) {                                       
            new FormPotong().setVisible(true);        // TODO add your handling code here:
    }                                      

    private void HitamPutihActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
        //Pemasukan treshold
        String string;
        String inputHitput = "";
        do{
            string = JOptionPane.showInputDialog("Masukan treshold!");
            if(string.matches("^[0-9]*$")){
                inputHitput = string;
            }else{
                JOptionPane.showMessageDialog(null, "Masukkan angka saja!");
            }
        }while(!inputHitput.matches("^[0-9]*$"));

        int treshold = Integer.parseInt(inputHitput);
        

        //Mulai perubahan citra
        BufferedImage img = null;
        File f = null;

        //Masukin lokasi gambarnya
        try{
          f = new File(ImgDir);             //di sini harus bener direktorinya
          img = ImageIO.read(f);
        }catch(IOException e){
          System.out.println(e);                                                    //cek eror
        }
    
        //PENTING buat tau ukuran gambarnya
        int width = img.getWidth();
        int height = img.getHeight();

        for(int y = 0; y < height; y++){
            for(int x = 0; x < width; x++){
              int p = img.getRGB(x,y);
      
              int a = (p>>24)&0xff;
              int r = (p>>16)&0xff;
              int g = (p>>8)&0xff;
              int b = p&0xff;
              int avg = (r+g+b)/3;                                                    //Ini hasil rata-rata dari nilai argb buat dimasukin nanti
      
              if(avg > treshold){
                  r = g = b = 255;
              }else{
                  r = g = b = 0;
              }
              p = (a<<24) | (r<<16) | (g<<8) | b;                               //ini masukin warna baru ke gambar
      
              //Ini tresholdnya 120 jadi pake syarat kalo di atas 120 rgb dibikin 255/putih kalo di bawah dibikin 0/hitam
      
              img.setRGB(x, y, p);
            }
        }

        Image resized = img.getScaledInstance(550, 450, Image.SCALE_DEFAULT);
        
        ImageIcon icon = new ImageIcon(resized);
        GambarDisini.setIcon(icon);
    }                                          

    private void NegatifActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        //Mulai perubahan citra
        BufferedImage img = null;
        File f = null;

        //Masukin lokasi gambarnya
        try{
          f = new File(ImgDir);            
          img = ImageIO.read(f);
        }catch(IOException e){
          System.out.println(e);                                           
        }
    
        //PENTING buat tau ukuran gambarnya
        int width = img.getWidth();
        int height = img.getHeight();
        for(int y = 0; y < height; y++){
            for(int x = 0; x < width; x++){
              int p = img.getRGB(x,y);
      
              int a = (p>>24)&0xff;
              int r = (p>>16)&0xff;
              int g = (p>>8)&0xff;
              int b = p&0xff;
      
              r = 255 - r;
              g = 255 - g;
              b = 255 - b;
              //Semua piksel harus pake rumus 255 - rgb biar dapet warna negatifnya
              p = (a<<24) | (r<<16) | (g<<8) | b;                               //ini masukin warna baru ke gambar
      
              img.setRGB(x, y, p);
            }
        }
        Image resized = img.getScaledInstance(550, 450, Image.SCALE_DEFAULT);
        
        ImageIcon icon = new ImageIcon(resized);
        GambarDisini.setIcon(icon);
    }                                       

    private void GrayscaleActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        //Mulai perubahan citra
        BufferedImage img = null;
        File f = null;

        //Masukin lokasi gambarnya
        try{
          f = new File(ImgDir);            
          img = ImageIO.read(f);
        }catch(IOException e){
          System.out.println(e);                                           
        }
    
        //PENTING buat tau ukuran gambarnya
        int width = img.getWidth();
        int height = img.getHeight();

        //algoritma yang rubah warna jadi hitam-putih di sini
        for(int y = 0; y < height; y++){
            for(int x = 0; x < width; x++){
              int p = img.getRGB(x,y);
      
              int a = (p>>24)&0xff;
              int r = (p>>16)&0xff;
              int g = (p>>8)&0xff;
              int b = p&0xff;
              int avg = (r+g+b)/3;                                                    //Ini hasil rata-rata dari nilai argb buat dimasukin nanti
  
              p = (a<<24) | (avg<<16) | (avg<<8) | avg;                               //ini masukin warna baru ke gambar
      
              //Ini tresholdnya 120 jadi pake syarat kalo di atas 120 rgb dibikin 255/putih kalo di bawah dibikin 0/hitam
      
              img.setRGB(x, y, p);
            }
          }
          Image resized = img.getScaledInstance(550, 450, Image.SCALE_DEFAULT);
        
          ImageIcon icon = new ImageIcon(resized);
        GambarDisini.setIcon(icon);
    }                                         

    private void ZoomBesarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void ZoomKecilActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void CerminAtasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
    }                                          

    private void CerminKiriActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        BufferedImage img = null;
        File f = null;

        //Masukin lokasi gambarnya
        try{
          f = new File(ImgDir);            
          img = ImageIO.read(f);
        }catch(IOException e){
          System.out.println(e);                                           
        }
    
        //PENTING buat tau ukuran gambarnya
        int width = img.getWidth();
        int height = img.getHeight();

        BufferedImage mimg = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        //create mirror image pixel by pixel
        for(int y = 0; y < height; y++){
            for(int lx = 0, rx = width - 1; lx < width; lx++, rx--){
                //lx mulai dari sisi kiri, rx dari kanan
                int p = img.getRGB(lx, y);
                mimg.setRGB(rx, y, p);
            }
        }
        Image resized = mimg.getScaledInstance(550, 450, Image.SCALE_DEFAULT);
        
        ImageIcon icon = new ImageIcon(resized);
        GambarDisini.setIcon(icon);
    }                                          

    private void RotasiKiriActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void aturKecerahan(javax.swing.event.ChangeEvent evt) {                               
        // TODO add your handling code here:
        //Pemasukan treshold
        int temp = KecerahanSlide.getValue();
        int treshold = temp - 100;

        //Mulai perubahan citra
        BufferedImage img = null;
        File f = null;

        //Masukin lokasi gambarnya
        try{
          f = new File(ImgDir);            
          img = ImageIO.read(f);
        }catch(IOException e){
          System.out.println(e);                                           
        }
    
        //PENTING buat tau ukuran gambarnya
        int width = img.getWidth();
        int height = img.getHeight();

        for(int y = 0; y < height; y++){
            for(int x = 0; x < width; x++){
              int p = img.getRGB(x,y);
      
              int a = (p>>24)&0xff;
              int r = (p>>16)&0xff;
              int g = (p>>8)&0xff;
              int b = p&0xff;
      
              r = r + treshold;
              g = g + treshold;
              b = b + treshold;
              if(r > 255){
                r = 255;
              }
              if(g > 255){
                g = 255;
              }
              if(b > 255){
                b = 255;
              }
              if(r < 0){
                r = 0;
              }
              if(g < 0){
                g = 0;
              }
              if(b < 0){
                b = 0;
              }
              //Harus pake syarat batas... gw lagi cari cara buat nyederhanain
      
              p = (a<<24) | (r<<16) | (g<<8) | b;                             //ini masukin warna baru ke gambar
      
              img.setRGB(x, y, p);
            }
        }
        Image resized = img.getScaledInstance(550, 450, Image.SCALE_DEFAULT);
        
        ImageIcon icon = new ImageIcon(resized);
        GambarDisini.setIcon(icon);

    }                              

    private void statusCekKecerahan(javax.swing.event.ChangeEvent evt) {                                    
        // TODO add your handling code here:
        if(CheckKecerahan.isSelected()){
            KecerahanSlide.setEnabled(true);
        }else{
            KecerahanSlide.setEnabled(false);
        }
    }                                   

    //Variabel yang mungkin bantu... entahlah
    String ImgDir;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CerminAtas;
    private javax.swing.JButton CerminKiri;
    private javax.swing.JCheckBox CheckKecerahan;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JLabel GambarDisini;
    private javax.swing.JMenuItem Grayscale;
    private javax.swing.JMenuItem HitamPutih;
    private javax.swing.JSlider KecerahanSlide;
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenuItem LoadGambar;
    private javax.swing.JMenuBar MenuUtama;
    private javax.swing.JMenuItem Negatif;
    private javax.swing.JButton Potong;
    private javax.swing.JLabel Rotasi;
    private javax.swing.JButton RotasiKanan;
    private javax.swing.JButton RotasiKiri;
    private javax.swing.JLabel Zoom;
    private javax.swing.JButton ZoomBesar;
    private javax.swing.JButton ZoomKecil;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar2;
    // End of variables declaration                   
}
